'use strict';
// Builds macse-dp-wasm.js: the AssemblyScript kernel tests/macse-port/dpcore.ts (generated by gen_dp.js) compiled to
// WebAssembly and embedded as base64, so that workers can load it with importScripts and Node with require.
// node tests/macse-port/build_wasm.js            (runs gen_dp.js first; needs network access for npx assemblyscript)
const fs = require('fs'), path = require('path'), cp = require('child_process'), crypto = require('crypto'), os = require('os');
const here = __dirname, root = path.join(here, '..', '..');
cp.execFileSync(process.execPath, [path.join(here, 'gen_dp.js')], { stdio: 'inherit' });
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'macse-wasm-'));
const ts = path.join(tmp, 'dpcore.ts'), wasm = path.join(tmp, 'dpcore.wasm');
fs.copyFileSync(path.join(here, 'dpcore.ts'), ts);
const ASC_VERSION = '0.27.37';
cp.execSync(`npx --yes -p assemblyscript@${ASC_VERSION} asc "${ts}" -O3 --runtime stub --noAssert --importMemory -o "${wasm}"`, { stdio: 'inherit', cwd: tmp });
const bytes = fs.readFileSync(wasm);
const sha = crypto.createHash('sha256').update(bytes).digest('hex');
const b64 = bytes.toString('base64');
const lines = b64.match(/.{1,120}/g).map(l => `        '${l}'`).join(' +\n');
const out = `'use strict';
// GENERATED by tests/macse-port/build_wasm.js; do not edit. WebAssembly build of the dynamic-programming kernel of
// macse-align.js (tests/macse-port/dpcore.ts, AssemblyScript ${ASC_VERSION}, -O3), base64. sha256 of the wasm: ${sha}
// Part of macse-align.js, a port of MACSE v2.07 (Ranwez et al.), distributed under CeCILL 2.1 (LICENSE-MACSE).
(function (root) {
    const b64 =
${lines};
    if (typeof module === 'object' && module.exports) module.exports = b64;
    root.MacseDpWasm = b64;
}(typeof self !== 'undefined' ? self : this));
`;
fs.writeFileSync(path.join(root, 'macse-dp-wasm.js'), out);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`macse-dp-wasm.js written: ${bytes.length} bytes of wasm, sha256 ${sha}`);
