// Classify the probe's results (results.json) into conflict findings.
// Usage: node dev-tools/colour-conflicts/analyze.js [results.json] > report.md
const fs = require('fs');
const path = require('path');
const file = process.argv[2] || path.join(__dirname, 'results.json');
const R = JSON.parse(fs.readFileSync(file, 'utf8'));
const ids = Object.keys(R.layers);
const L = id => R.layers[id];

// Flatten a sig into channel -> value ("cell.backgroundColor": "rgb(...)")
function flat(s) {
  const o = {};
  if (!s) return o;
  for (const part of ['cell', 'name', 'row']) {
    for (const [k, v] of Object.entries(s[part] || {})) o[`${part}.${k}`] = v;
  }
  o['overlay'] = String(s.overlay || 0);
  return o;
}
const base = flat(R.base);
const eff = id => {                       // channels a layer changes on its own
  const on = flat(R.single[id].on);
  return Object.keys(on).filter(k => on[k] !== base[k]);
};
const same = (x, y) => JSON.stringify(flat(x)) === JSON.stringify(flat(y));
const diffKeys = (x, y) => { const a = flat(x), b = flat(y); return Object.keys({ ...a, ...b }).filter(k => a[k] !== b[k]); };
const short = k => k.replace('cell.', '').replace('name.', 'name ').replace('row.', 'row ')
  .replace('backgroundColor', 'bg').replace('fontWeight', 'weight').replace('textDecorationLine', 'underline')
  .replace('outlineStyle', 'outline').replace('boxShadow', 'shadow');

const lines = [];
const p = s => lines.push(s);

p(`# Colour / marking conflict matrix\n`);
p(`Target: residue at row ${R.row}, column ${R.col} (0-based), its name cell and its row. ` +
  `DOM mode (Full view) unless stated. Generated by dev-tools/colour-conflicts/probe.js.\n`);

// ---- single layers ----
p(`## Each layer alone\n`);
p(`| Layer | Changes (DOM) | Survives redraw | Clear restores | Canvas shows it | Page errors |`);
p(`|---|---|---|---|---|---|`);
for (const id of ids) {
  const s = R.single[id];
  const e = eff(id).map(short).join(', ') || '(nothing at target)';
  const cv = R.canvas?.[id] && R.canvas?.base
    ? ((R.canvas[id].cell !== R.canvas.base.cell || R.canvas[id].name !== R.canvas.base.name) ? 'yes' : 'NO') : '?';
  p(`| ${L(id)} | ${e} | ${same(s.on, s.redraw) ? 'yes' : '**NO** (' + diffKeys(s.on, s.redraw).map(short).join(', ') + ')'} | ${same(s.off, R.base) ? 'yes' : '**NO** (' + diffKeys(s.off, R.base).map(short).join(', ') + ')'} | ${cv} | ${s.errors.length ? s.errors.join('; ').slice(0, 80) : ''} |`);
}

// ---- pairs ----
const findings = [];
for (const [key, r] of Object.entries(R.pairs)) {
  const [a, b] = key.split('|');
  const ea = eff(a), eb = eff(b);
  const A = flat(R.single[a].on), B = flat(R.single[b].on), AB = flat(r.ab), BA = flat(r.ba);
  const f = { a, b, kinds: [], notes: [] };
  // who wins each shared channel
  const shared = ea.filter(k => eb.includes(k));
  const winners = shared.map(k => {
    const w = x => (x[k] === A[k] ? a : x[k] === B[k] ? b : 'mix');
    return { k, ab: w(AB), ba: w(BA) };
  });
  const hidden = id => {
    const e = id === a ? ea : eb, other = id === a ? B : A;
    return e.length > 0 && e.every(k => AB[k] === other[k] && BA[k] === other[k]);
  };
  if (hidden(a)) f.kinds.push(`hidden:${a}`);
  if (hidden(b)) f.kinds.push(`hidden:${b}`);
  if (!same(r.ab, r.ba)) { f.kinds.push('order'); f.notes.push('A,B vs B,A differ in ' + diffKeys(r.ab, r.ba).map(short).join(', ')); }
  if (!same(r.abClearB, R.single[a].on)) { f.kinds.push(`clear-${b}-breaks-${a}`); f.notes.push(`after clearing ${b}: ` + diffKeys(r.abClearB, R.single[a].on).map(short).join(', ') + ` differ from ${a} alone`); }
  if (!same(r.baClearA, R.single[b].on)) { f.kinds.push(`clear-${a}-breaks-${b}`); f.notes.push(`after clearing ${a}: ` + diffKeys(r.baClearA, R.single[b].on).map(short).join(', ') + ` differ from ${b} alone`); }
  if (!same(r.abRedraw, r.ab)) { f.kinds.push('redraw'); f.notes.push('redraw changes ' + diffKeys(r.ab, r.abRedraw).map(short).join(', ')); }
  if (!same(r.abClearBoth, R.base)) { f.kinds.push('residue'); f.notes.push('both cleared, left behind: ' + diffKeys(r.abClearBoth, R.base).map(short).join(', ')); }
  if ((r.errorsAB || []).length || (r.errorsBA || []).length) { f.kinds.push('error'); f.notes.push([...(r.errorsAB || []), ...(r.errorsBA || [])].join('; ').slice(0, 160)); }
  f.winners = winners;
  findings.push(f);
}

const bad = findings.filter(f => f.kinds.length);
p(`\n## Pairs with a conflict (${bad.length} of ${findings.length})\n`);
p(`Kinds: **hidden:X** X cannot be seen at all when both are on; **order** the result depends on which ran last; ` +
  `**clear-X-breaks-Y** removing X does not give back Y's own look; **redraw** a redraw changes the look; ` +
  `**residue** removing both leaves something behind.\n`);
p(`| A | B | Kinds | Shared channels: winner (A,B order / B,A order) | Details |`);
p(`|---|---|---|---|---|`);
for (const f of bad) {
  const w = f.winners.map(x => `${short(x.k)}: ${x.ab === x.ba ? x.ab : x.ab + ' / ' + x.ba}`).join('; ');
  p(`| ${L(f.a)} | ${L(f.b)} | ${f.kinds.join(', ')} | ${w} | ${f.notes.join('. ')} |`);
}

// kind counts per layer
p(`\n## Conflict count per layer\n`);
p(`| Layer | hidden by others | hides others | order | clear breaks | redraw |`);
p(`|---|---|---|---|---|---|`);
for (const id of ids) {
  const mine = bad.filter(f => f.a === id || f.b === id);
  const hiddenBy = mine.filter(f => f.kinds.includes(`hidden:${id}`)).map(f => L(f.a === id ? f.b : f.a));
  const hides = mine.filter(f => f.kinds.some(k => k.startsWith('hidden:') && k !== `hidden:${id}`)).map(f => L(f.a === id ? f.b : f.a));
  p(`| ${L(id)} | ${hiddenBy.join(', ')} | ${hides.join(', ')} | ${mine.filter(f => f.kinds.includes('order')).length} | ${mine.filter(f => f.kinds.some(k => k.startsWith('clear-'))).length} | ${mine.filter(f => f.kinds.includes('redraw')).length} |`);
}
console.log(lines.join('\n'));
fs.writeFileSync(path.join(__dirname, 'findings.json'), JSON.stringify(findings, null, 1));
